server:
  port: 0
spring:
  application:
    name: cart-service
  datasource: 
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.150.222.61:3306/Book_Demo_DB  

 
 