server:
  port: 0
spring:
  application:
    name: book-inventory
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.150.222.61:3306/Book_Demo_DB
    username: root
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  
   